name: Java CI

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn -f ./neptunclone/pom.xml compile
      - name: Test with Maven
        run: mvn -f ./neptunclone/pom.xml test
      - name: Coverage with JaCoCo
        if: always()
        run: mvn -f ./neptunclone/pom.xml jacoco:report
      - name: Publish coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: neptun-clone-coverage
          path: ./neptunclone/target/site/jacoco